const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const SHOW_MODAL = 'SHOW_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';

export {
  CHANGE_LANGUAGE,
  SHOW_MODAL,
  CLOSE_MODAL,
  START_LOADING,
  STOP_LOADING,
};
